version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    restart: unless-stopped
    ports:
      - 6000:80
    environment:
      - SERVICE_80_NAME=blog-test_threeq_me
      - SERVICE_80_TAGS=open_web,path:/,host:blog-test.threeq.me

